# Generated by Django 3.0.8 on 2020-08-01 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_host', models.BooleanField()),
                ('name', models.CharField(max_length=30)),
                ('player_number', models.IntegerField()),
                ('question1', models.BooleanField()),
                ('question2', models.BooleanField()),
                ('question3', models.BooleanField()),
                ('question4', models.BooleanField()),
                ('question5', models.BooleanField()),
                ('question6', models.BooleanField()),
                ('question7', models.BooleanField()),
                ('question8', models.BooleanField()),
                ('question9', models.BooleanField()),
                ('question10', models.BooleanField()),
            ],
        ),
    ]
