# Generated by Django 2.0.13 on 2020-08-02 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200802_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='current_guess',
            field=models.IntegerField(default=0),
        ),
    ]
